name: Vue.js App CI/CD Pipeline

# Xác định sự kiện trigger cho pipeline
on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build và push Docker image
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create entrypoint script
        run: |
          echo '#!/bin/bash' > docker-entrypoint.sh
          echo 'sed -i "s|__VITE_APP_ROOT_API__|$VITE_APP_ROOT_API|g" /usr/share/nginx/html/config.js' >> docker-entrypoint.sh
          echo 'sed -i "s|__VITE_APP_WEBSOCKET_URL__|$VITE_APP_WEBSOCKET_URL|g" /usr/share/nginx/html/config.js' >> docker-entrypoint.sh
          echo 'exec nginx -g "daemon off;"' >> docker-entrypoint.sh
          chmod +x docker-entrypoint.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build và push image lên Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            VITE_APP_ROOT_API=${{ secrets.VITE_APP_ROOT_API }}
            VITE_APP_WEBSOCKET_URL=${{ secrets.VITE_APP_WEBSOCKET_URL }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vuejs-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vuejs-app:${{ github.sha }}

  # Job 2: Deploy
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull image mới nhất từ Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vuejs-app:${{ github.sha }}

            # Dừng và gỡ bỏ container hiện tại (nếu có)
            docker stop vuejs-container || true
            docker rm vuejs-container || true
            docker images